import operator
from typing import Annotated, List, Optional, TypedDict
from pydantic import BaseModel, Field
from typing_extensions import TypedDict

# ==========================================
# 1. STRUCTURED OUTPUT MODELS (For the LLM)
# ==========================================

class CompanyIntel(BaseModel):
    """Structured data extracted by the Research Agent from the website."""
    company_name: str = Field(description="The formal name of the company.")
    core_product: str = Field(description="A concise description of their primary product or service.")
    target_audience: str = Field(description="Who they sell to (e.g., B2B enterprise, B2C consumer, developers).")
    value_proposition: str = Field(description="The core problem they claim to solve for their users.")
    estimated_tech_stack: List[str] = Field(description="Any visible cloud/tech stack mentions (e.g., AWS, AI, SaaS).")

class LeadQualification(BaseModel):
    """The strict evaluation structure filled out by the Qualification Agent."""
    is_fit: bool = Field(description="True if the company matches the target B2B Ideal Customer Profile (ICP), False otherwise.")
    confidence_score: float = Field(description="Confidence score from 0.0 to 1.0 regarding the evaluation.")
    justification: str = Field(description="Detailed technical or business reasoning behind the fit/no-fit decision.")

class OutreachDraft(BaseModel):
    """The hyper-personalized email payload generated by the Copywriter Agent."""
    subject_line: str = Field(description="A compelling, context-aware email subject line.")
    email_body: str = Field(description="The complete, personalized cold outreach email body.")
    personalized_hook: str = Field(description="The specific line referencing their actual product or data point.")

# ==========================================
# 2. LANGGRAPH STATE DEFINITION
# ==========================================

class AgentState(TypedDict):
    """The state object flowing through our LangGraph state machine workflow."""
    domain: str                           # User input: the domain url to research
    raw_web_text: Optional[str]           # Intermediate data: cleaned text from scraping
    intel: Optional[CompanyIntel]         # Filled by Research Agent
    qualification: Optional[LeadQualification]  # Filled by Qualification Agent
    outreach: Optional[OutreachDraft]     # Filled by Copywriter Agent
    status: Optional[str]                 # Execution pipeline routing status
    
    # Using operator.add lets parallel nodes safely append logs concurrently!
    logs: Annotated[List[str], operator.add]